# Generated by Django 3.0.6 on 2020-05-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=32)),
                ('deptcode', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=32)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('mac', models.CharField(max_length=32, null=True)),
                ('os', models.CharField(default='WindowsServer2012', max_length=32)),
                ('price', models.CharField(max_length=10, null=True)),
                ('cpu', models.CharField(max_length=32, null=True)),
                ('memory', models.CharField(max_length=32, null=True)),
                ('disk', models.CharField(max_length=32, null=True)),
                ('power', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Business')),
            ],
        ),
    ]
