# Generated by Django 3.0.6 on 2020-05-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ippool',
            fields=[
                ('ipid', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.GenericIPAddressField(db_index=True)),
                ('netmask', models.CharField(max_length=20, null=True)),
                ('gateway', models.CharField(max_length=20, null=True)),
                ('dns', models.CharField(max_length=20, null=True)),
                ('ip_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '个人PC'), (3, '其他')], default=2)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('relgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Business')),
            ],
        ),
    ]
