# Generated by Django 3.0.6 on 2020-06-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200601_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='mac',
            new_name='Extranetmac',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='IntraneDNS',
            new_name='IntranetDNS',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='IntraneGateWay',
            new_name='IntranetGateWay',
        ),
        migrations.AddField(
            model_name='host',
            name='CPUlogiccores',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='CPUphysicalcores',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='Intranetmac',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mainboardNo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mainboardmodel',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='systemVersion',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
