# Generated by Django 3.0.6 on 2020-06-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200602_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='Extranetname',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='Intranetname',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
