# Generated by Django 3.0.6 on 2020-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_ippool_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ippool',
            name='ip_type_id',
        ),
        migrations.AddField(
            model_name='ippool',
            name='ip_type',
            field=models.CharField(default='个人IP', max_length=20, null=True),
        ),
    ]
